### ISSUE TITLE
Cannot find module 'express'

### ISSUE THREAD

**Issue by devinrhode2** [joostdevries/ember-cli-remote-inspector#8]
Ember-cli 0.2.0 removes express from package.json, and this addon assumes it'll be there.. so somehow this addon needs to get express into the picture

(Well, technically it's the `ember init` from ember-cli 0.2.0 that removes this)

**Comment by devotox** [comment]
Is this still being looked at?

**Comment by devinrhode2** [comment]
you're sure you have npm installed?

**Comment by joostdevries** [comment]
Just put some more work in #7. Once I have feedback on that, I'll merge + release. Sorry for the delay guys.
